defaults:
  lvmConsumption: 100
devices:
  /dev/vdb:
    fs: xfs
    lvm: ifmx-var
    mountPoint: /mnt/foo
    user: ubuntu
    group: ubuntu
    permissions: 755
    resize: true
    resizeThreshold: 99