name: Build and Test 🔨
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    name: Build and Test (${{ matrix.architecture }}) 🔨
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.architecture }}
      - name: Build and Test 🔨
        run: ./build/docker.sh --architecture ${{ matrix.architecture }}
